"use client";

import { useState } from "react";
import { Clock3, Edit3, Flame, Plus, Sparkles, Target, Trophy, X } from "lucide-react";

type Category = { id: string; name: string; slug: string; description: string; type: string; durationDays: number; targetAttendances: number; pointsPerAttendance: number; completionBonus: number; winnerBonus: number; status: string };
const empty: Category = { id: "", name: "", slug: "", description: "", type: "REACH_TARGET", durationDays: 15, targetAttendances: 15, pointsPerAttendance: 2, completionBonus: 15, winnerBonus: 10, status: "ACTIVE" };

export function ChallengeCategoryManager({ initial }: { initial: Category[] }) {
  const [rows, setRows] = useState(initial);
  const [editing, setEditing] = useState<Category>();
  const [message, setMessage] = useState("");
  const [saving, setSaving] = useState(false);
  async function submit(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault(); if (!editing) return; setSaving(true); setMessage("");
    const body = Object.fromEntries(new FormData(event.currentTarget));
    const response = await fetch(editing.id ? `/api/v1/admin/challenge-categories/${editing.id}` : "/api/v1/admin/challenge-categories", { method: editing.id ? "PATCH" : "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(body) });
    const json = await response.json() as { data?: Category; message: string; errors?: Array<{ message: string }> };
    setSaving(false); setMessage(response.ok ? json.message : (json.errors?.[0]?.message ?? json.message));
    if (!response.ok || !json.data) return;
    setRows((current) => editing.id ? current.map((row) => row.id === json.data!.id ? json.data! : row) : [json.data!, ...current]); setEditing(undefined);
  }
  return <div className="space-y-6">
    <div className="flex flex-wrap items-center justify-between gap-4"><div className="flex gap-3"><div className="rounded-2xl border border-slate-800 bg-slate-900/70 px-5 py-3"><strong className="text-2xl">{rows.length}</strong><span className="ml-2 text-xs muted">categorías</span></div><div className="rounded-2xl border border-slate-800 bg-slate-900/70 px-5 py-3"><strong className="text-2xl text-lime-300">{rows.filter((row) => row.status === "ACTIVE").length}</strong><span className="ml-2 text-xs muted">activas</span></div></div><button onClick={() => { setEditing(empty); setMessage(""); }} className="btn gap-2"><Plus size={18}/>Crear reto</button></div>
    {message && <p role="status" className="rounded-2xl border border-orange-400/20 bg-orange-400/5 p-4 text-sm font-bold text-orange-200">{message}</p>}
    <div className="grid gap-5 md:grid-cols-2 xl:grid-cols-3">{rows.map((row) => <article key={row.id} className="group overflow-hidden rounded-[28px] border border-slate-800 bg-gradient-to-br from-orange-400/10 via-slate-900 to-slate-950 p-6 transition hover:border-orange-400/40"><div className="flex items-start justify-between"><span className="grid h-12 w-12 place-items-center rounded-2xl bg-orange-400/15 text-orange-300"><Flame size={25}/></span><span className={`rounded-full px-3 py-1 text-[10px] font-black ${row.status === "ACTIVE" ? "bg-lime-400/10 text-lime-300" : "bg-slate-700 text-slate-300"}`}>{row.status === "ACTIVE" ? "ACTIVO" : "INACTIVO"}</span></div><h3 className="mt-5 text-2xl font-black">{row.name}</h3><p className="mt-1 text-xs font-bold text-orange-300">{row.slug}</p><p className="mt-3 min-h-16 text-sm muted">{row.description}</p><div className="mt-5 grid grid-cols-2 gap-2 text-xs"><span className="rounded-xl bg-slate-950/70 p-3"><Clock3 size={15} className="mb-1 text-cyan-300"/>{row.durationDays} días</span><span className="rounded-xl bg-slate-950/70 p-3"><Target size={15} className="mb-1 text-lime-300"/>{row.targetAttendances} asistencias</span><span className="rounded-xl bg-slate-950/70 p-3"><Sparkles size={15} className="mb-1 text-violet-300"/>+{row.pointsPerAttendance} por día</span><span className="rounded-xl bg-slate-950/70 p-3"><Trophy size={15} className="mb-1 text-yellow-300"/>Bono +{row.completionBonus}</span></div><button onClick={() => { setEditing(row); setMessage(""); }} className="mt-5 flex w-full items-center justify-center gap-2 rounded-xl border border-slate-700 py-3 font-bold transition hover:border-orange-400 hover:text-orange-300"><Edit3 size={16}/>Editar configuración</button></article>)}</div>
    {editing && <div className="fixed inset-0 z-[80] overflow-y-auto bg-black/80 p-3 backdrop-blur-lg sm:grid sm:place-items-center sm:p-6"><form onSubmit={submit} className="my-auto w-full max-w-3xl overflow-hidden rounded-[30px] border border-slate-700 bg-slate-900"><div className="flex items-start justify-between border-b border-slate-800 bg-gradient-to-r from-orange-400/10 to-lime-400/5 p-5"><div><p className="text-xs font-black text-orange-300">DISEÑADOR DE RETOS</p><h2 className="mt-1 text-2xl font-black">{editing.id ? "Editar reto" : "Nueva categoría"}</h2></div><button type="button" aria-label="Cerrar" onClick={() => setEditing(undefined)} className="rounded-full bg-slate-950 p-2"><X/></button></div><div className="grid gap-4 p-5 sm:grid-cols-2">
      <label className="text-sm font-bold">Nombre<input name="name" defaultValue={editing.name} required className="mt-2 w-full rounded-xl border border-slate-700 bg-slate-950 p-3"/></label><label className="text-sm font-bold">Slug<input name="slug" defaultValue={editing.slug} required className="mt-2 w-full rounded-xl border border-slate-700 bg-slate-950 p-3"/></label><label className="text-sm font-bold sm:col-span-2">Descripción<textarea name="description" defaultValue={editing.description} minLength={10} required rows={3} className="mt-2 w-full rounded-xl border border-slate-700 bg-slate-950 p-3"/></label><label className="text-sm font-bold">Modalidad<select name="type" defaultValue={editing.type} className="mt-2 w-full rounded-xl border border-slate-700 bg-slate-950 p-3"><option value="REACH_TARGET">Alcanzar meta</option><option value="MOST_ATTENDANCES">Más asistencias</option><option value="FIRST_TO_TARGET">Primero en llegar</option><option value="STREAK">Mejor racha</option></select></label><label className="text-sm font-bold">Estado<select name="status" defaultValue={editing.status} className="mt-2 w-full rounded-xl border border-slate-700 bg-slate-950 p-3"><option value="ACTIVE">Activo</option><option value="INACTIVE">Inactivo</option></select></label><label className="text-sm font-bold">Duración en días<input name="durationDays" type="number" min="1" defaultValue={editing.durationDays} required className="mt-2 w-full rounded-xl border border-slate-700 bg-slate-950 p-3"/></label><label className="text-sm font-bold">Meta de asistencias<input name="targetAttendances" type="number" min="1" defaultValue={editing.targetAttendances} required className="mt-2 w-full rounded-xl border border-slate-700 bg-slate-950 p-3"/></label><label className="text-sm font-bold">Puntos por asistencia<input name="pointsPerAttendance" type="number" min="0" defaultValue={editing.pointsPerAttendance} required className="mt-2 w-full rounded-xl border border-slate-700 bg-slate-950 p-3"/></label><label className="text-sm font-bold">Bono por completar<input name="completionBonus" type="number" min="0" defaultValue={editing.completionBonus} required className="mt-2 w-full rounded-xl border border-slate-700 bg-slate-950 p-3"/></label><label className="text-sm font-bold">Bono ganador<input name="winnerBonus" type="number" min="0" defaultValue={editing.winnerBonus} required className="mt-2 w-full rounded-xl border border-slate-700 bg-slate-950 p-3"/></label><button type="button" onClick={() => setEditing(undefined)} className="rounded-xl border border-slate-700 p-3 font-bold">Cancelar</button><button disabled={saving} className="btn">{saving ? "Guardando…" : "Guardar reto"}</button>
    </div></form></div>}
  </div>;
}
