"use client";

import { useState } from "react";
import { BarChart3, Check, Edit3, FileDown, Gauge, HardDrive, MessageCircle, Plus, Sparkles, UsersRound, WalletCards, X } from "lucide-react";

type Plan = { id: string; name: string; code: string; description: string | null; monthlyPrice: number; currency: string; status: string; trialDays: number; storageLimitMb: number; activeChallengeLimit: number; friendLimit: number; historyMonths: number | null; expensesEnabled: boolean; whatsappEnabled: boolean; advancedStatsEnabled: boolean; exportsEnabled: boolean; createdAt: string; updatedAt: string; _count: { subscriptions: number } };
const blank = { name: "", code: "", description: "", monthlyPrice: 0, currency: "COP", status: "ACTIVE", trialDays: 0, storageLimitMb: 1024, activeChallengeLimit: 3, friendLimit: 50, historyMonths: 12, expensesEnabled: false, whatsappEnabled: false, advancedStatsEnabled: false, exportsEnabled: false };

export function PlanManager({ initial }: { initial: Plan[] }) {
  const [plans, setPlans] = useState(initial);
  const [editing, setEditing] = useState<Plan>();
  const [message, setMessage] = useState("");
  const [saving, setSaving] = useState(false);

  async function submit(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault(); setSaving(true); setMessage("");
    const form = new FormData(event.currentTarget);
    const body: Record<string, unknown> = Object.fromEntries(form);
    for (const key of ["expensesEnabled", "whatsappEnabled", "advancedStatsEnabled", "exportsEnabled"]) body[key] = form.has(key);
    const url = editing?.id ? `/api/v1/admin/plans/${editing.id}` : "/api/v1/admin/plans";
    const response = await fetch(url, { method: editing?.id ? "PATCH" : "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(body) });
    const result = await response.json() as { data?: Plan; message: string; errors?: Array<{ message: string }> };
    setSaving(false); setMessage(response.ok ? result.message : (result.errors?.[0]?.message ?? result.message));
    if (!response.ok || !result.data) return;
    setPlans((current) => editing?.id ? current.map((plan) => plan.id === result.data!.id ? result.data! : plan) : [...current, result.data!].sort((a, b) => a.monthlyPrice - b.monthlyPrice));
    setEditing(undefined);
  }

  return <div className="space-y-6">
    <div className="flex gap-3 rounded-2xl border border-cyan-400/20 bg-cyan-400/[.06] p-4 text-sm text-cyan-100"><Gauge className="shrink-0 text-cyan-300"/><div><strong>Control real por plan</strong><p className="mt-1 text-cyan-100/70">Los cambios de almacenamiento, retos, amigos e historial se aplican automáticamente a todos los usuarios suscritos.</p></div></div>
    <div className="flex flex-wrap items-center justify-between gap-4"><div className="flex gap-3"><article className="rounded-2xl border border-slate-800 bg-slate-900/70 px-5 py-3"><strong className="text-2xl">{plans.length}</strong><span className="ml-2 text-xs muted">planes</span></article><article className="rounded-2xl border border-slate-800 bg-slate-900/70 px-5 py-3"><strong className="text-2xl">{plans.reduce((sum, plan) => sum + plan._count.subscriptions, 0)}</strong><span className="ml-2 text-xs muted">suscripciones</span></article></div><button onClick={() => { setEditing({ id: "", ...blank, createdAt: "", updatedAt: "", _count: { subscriptions: 0 } }); setMessage(""); }} className="btn gap-2"><Plus size={18}/>Crear plan</button></div>
    {message && <p role="status" className="rounded-2xl border border-violet-400/20 bg-violet-400/5 p-4 text-sm font-bold text-violet-200">{message}</p>}
    <div className="grid gap-5 md:grid-cols-2 xl:grid-cols-3">{plans.map((plan, index) => <article key={plan.id} className={`relative overflow-hidden rounded-[28px] border p-6 ${index === 1 ? "border-lime-400/40 bg-gradient-to-br from-lime-400/10 via-slate-900 to-slate-950 shadow-[0_0_50px_rgba(163,230,53,.08)]" : "border-slate-800 bg-slate-900/80"}`}>
      {index === 1 && <span className="absolute right-4 top-4 rounded-full bg-lime-400 px-3 py-1 text-[9px] font-black text-slate-950">DESTACADO</span>}<span className={`inline-flex rounded-full px-3 py-1 text-[10px] font-black ${plan.status === "ACTIVE" ? "bg-cyan-400/10 text-cyan-300" : "bg-slate-700 text-slate-300"}`}>{plan.status === "ACTIVE" ? "ACTIVO" : "INACTIVO"}</span><h2 className="mt-4 text-2xl font-black">{plan.name}</h2><p className="mt-1 text-xs font-bold text-violet-300">{plan.code}</p><p className="mt-4"><strong className="text-3xl font-black">{new Intl.NumberFormat("es-CO", { style: "currency", currency: plan.currency, maximumFractionDigits: 0 }).format(plan.monthlyPrice)}</strong><span className="text-sm muted"> / mes</span></p><p className="mt-3 min-h-10 text-sm muted">{plan.description || "Sin descripción comercial."}</p>
      <div className="mt-5 grid grid-cols-2 gap-2 text-xs"><span className="rounded-xl bg-slate-950/70 p-3"><HardDrive size={15} className="mb-1 text-cyan-300"/>{plan.storageLimitMb >= 1024 ? `${(plan.storageLimitMb / 1024).toFixed(plan.storageLimitMb % 1024 ? 1 : 0)} GB` : `${plan.storageLimitMb} MB`}</span><span className="rounded-xl bg-slate-950/70 p-3"><UsersRound size={15} className="mb-1 text-lime-300"/>{plan.friendLimit} amigos</span><span className="rounded-xl bg-slate-950/70 p-3"><Sparkles size={15} className="mb-1 text-orange-300"/>{plan.activeChallengeLimit} retos</span><span className="rounded-xl bg-slate-950/70 p-3"><WalletCards size={15} className="mb-1 text-violet-300"/>{plan.trialDays} días prueba</span></div>
      <div className="mt-4 flex flex-wrap gap-2">{plan.whatsappEnabled && <span className="inline-flex items-center gap-1 rounded-full bg-lime-400/10 px-2 py-1 text-[10px] font-bold text-lime-300"><MessageCircle size={11}/>WhatsApp</span>}{plan.advancedStatsEnabled && <span className="inline-flex items-center gap-1 rounded-full bg-lime-400/10 px-2 py-1 text-[10px] font-bold text-lime-300"><BarChart3 size={11}/>Estadísticas</span>}{plan.exportsEnabled && <span className="inline-flex items-center gap-1 rounded-full bg-lime-400/10 px-2 py-1 text-[10px] font-bold text-lime-300"><FileDown size={11}/>Exportaciones</span>}</div>
      <button onClick={() => { setEditing(plan); setMessage(""); }} className="mt-5 flex w-full items-center justify-center gap-2 rounded-xl border border-slate-700 py-3 font-bold transition hover:border-violet-400 hover:text-violet-300"><Edit3 size={16}/>Editar plan</button>
    </article>)}</div>

    {editing !== undefined && <div className="fixed inset-0 z-[80] overflow-y-auto bg-black/80 p-3 backdrop-blur-lg sm:grid sm:place-items-center sm:p-6"><form onSubmit={submit} className="my-auto w-full max-w-3xl overflow-hidden rounded-[30px] border border-slate-700 bg-slate-900"><div className="flex items-start justify-between border-b border-slate-800 bg-gradient-to-r from-violet-400/10 to-cyan-400/5 p-5"><div><p className="text-xs font-black text-violet-300">OFERTA COMERCIAL</p><h2 className="mt-1 text-2xl font-black">{editing.id ? "Editar plan" : "Nuevo plan"}</h2></div><button type="button" aria-label="Cerrar" onClick={() => setEditing(undefined)} className="rounded-full bg-slate-950 p-2"><X/></button></div><div className="grid gap-4 p-5 sm:grid-cols-2">
      <label className="text-sm font-bold">Nombre<input name="name" defaultValue={editing.name} required className="mt-2 w-full rounded-xl border border-slate-700 bg-slate-950 p-3"/></label><label className="text-sm font-bold">Código<input name="code" defaultValue={editing.code} required placeholder="PRO" className="mt-2 w-full rounded-xl border border-slate-700 bg-slate-950 p-3 uppercase"/></label><label className="text-sm font-bold">Precio mensual<input name="monthlyPrice" type="number" min="0" defaultValue={editing.monthlyPrice} required className="mt-2 w-full rounded-xl border border-slate-700 bg-slate-950 p-3"/></label><label className="text-sm font-bold">Estado<select name="status" defaultValue={editing.status} className="mt-2 w-full rounded-xl border border-slate-700 bg-slate-950 p-3"><option value="ACTIVE">Activo</option><option value="INACTIVE">Inactivo</option></select></label><label className="text-sm font-bold sm:col-span-2">Descripción<textarea name="description" defaultValue={editing.description ?? ""} rows={2} className="mt-2 w-full rounded-xl border border-slate-700 bg-slate-950 p-3"/></label><input type="hidden" name="currency" value={editing.currency}/>
      <div className="sm:col-span-2"><p className="text-xs font-black tracking-wider text-cyan-300">LÍMITES DEL PRODUCTO</p><p className="mt-1 text-xs muted">Se validan en el servidor; el usuario no puede superarlos desde la aplicación.</p></div><label className="text-sm font-bold">Días de prueba<input name="trialDays" type="number" min="0" defaultValue={editing.trialDays} required className="mt-2 w-full rounded-xl border border-slate-700 bg-slate-950 p-3"/><span className="mt-1 block text-[11px] font-normal muted">0 para planes sin periodo de prueba.</span></label><label className="text-sm font-bold">Almacenamiento total (MB)<input name="storageLimitMb" type="number" min="0" defaultValue={editing.storageLimitMb} required className="mt-2 w-full rounded-xl border border-slate-700 bg-slate-950 p-3"/><span className="mt-1 block text-[11px] font-normal muted">Incluye fotografías iniciales y finales.</span></label><label className="text-sm font-bold">Retos activos por usuario<input name="activeChallengeLimit" type="number" min="0" defaultValue={editing.activeChallengeLimit} required className="mt-2 w-full rounded-xl border border-slate-700 bg-slate-950 p-3"/><span className="mt-1 block text-[11px] font-normal muted">Cuenta retos creados, aceptados y pendientes.</span></label><label className="text-sm font-bold">Máximo de amigos<input name="friendLimit" type="number" min="0" defaultValue={editing.friendLimit} required className="mt-2 w-full rounded-xl border border-slate-700 bg-slate-950 p-3"/><span className="mt-1 block text-[11px] font-normal muted">Se valida al enviar y aceptar solicitudes.</span></label><label className="text-sm font-bold">Historial visible (meses)<input name="historyMonths" type="number" min="1" defaultValue={editing.historyMonths ?? ""} placeholder="Vacío = sin límite" className="mt-2 w-full rounded-xl border border-slate-700 bg-slate-950 p-3"/><span className="mt-1 block text-[11px] font-normal muted">Déjalo vacío para conservar todo el historial.</span></label>
      <div className="grid gap-2 rounded-2xl border border-slate-800 bg-slate-950/60 p-4 sm:col-span-2 sm:grid-cols-2">{[["whatsappEnabled","Integración WhatsApp",editing.whatsappEnabled],["advancedStatsEnabled","Estadísticas avanzadas",editing.advancedStatsEnabled],["exportsEnabled","Exportaciones",editing.exportsEnabled],["expensesEnabled","Control de gastos",editing.expensesEnabled]].map(([name,label,checked]) => <label key={String(name)} className="flex items-center gap-2 text-sm"><input type="checkbox" name={String(name)} defaultChecked={Boolean(checked)}/><Check size={14} className="text-lime-300"/>{label}</label>)}</div><button type="button" onClick={() => setEditing(undefined)} className="rounded-xl border border-slate-700 p-3 font-bold">Cancelar</button><button disabled={saving} className="btn">{saving ? "Guardando…" : "Guardar plan"}</button>
    </div></form></div>}
  </div>;
}
