"use client";
import { useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { ArrowLeft, ArrowRight, Check, CirclePause, CirclePlay, Clock3, Dumbbell, Flag, RotateCcw, X } from "lucide-react";
import { ExerciseVisual } from "./exercise-visual";

type ExerciseItem={id:string;sets:number;reps:number|null;durationSeconds:number|null;restSeconds:number;exercise:{id:string;name:string;nameEs:string|null;target:string;equipment:string;instructionsEs:string;instructionStepsEs:string[]}};
type Workout={id:string;status:string;accumulatedSeconds:number;segmentStartedAt:string|null;currentExerciseIndex:number;setLogs:{routineExerciseId:string;setNumber:number}[];routine:{name:string;exercises:ExerciseItem[]}};
const clock=(seconds:number)=>`${String(Math.floor(seconds/60)).padStart(2,"0")}:${String(seconds%60).padStart(2,"0")}`;

export function WorkoutRunner({ initialWorkout, licensed }: { initialWorkout: Workout; licensed: boolean }) {
  const router=useRouter(); const [workout,setWorkout]=useState(initialWorkout); const [now,setNow]=useState(Date.now()); const [busy,setBusy]=useState(""); const [rest,setRest]=useState(0); const [message,setMessage]=useState("");
  const index=Math.min(workout.currentExerciseIndex,Math.max(0,workout.routine.exercises.length-1)); const item=workout.routine.exercises[index]!;
  useEffect(()=>{const timer=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(timer)},[]);
  useEffect(()=>{if(rest<=0)return;const timer=setInterval(()=>setRest(value=>Math.max(0,value-1)),1000);return()=>clearInterval(timer)},[rest]);
  const elapsed=useMemo(()=>workout.accumulatedSeconds+(workout.status==="ACTIVE"&&workout.segmentStartedAt?Math.max(0,Math.floor((now-new Date(workout.segmentStartedAt).getTime())/1000)):0),[workout,now]);
  const complete=new Set(workout.setLogs.map(log=>`${log.routineExerciseId}:${log.setNumber}`)); const totalSets=workout.routine.exercises.reduce((sum,row)=>sum+row.sets,0); const percentage=Math.round((complete.size/Math.max(1,totalSets))*100);
  async function action(actionName:string,currentExerciseIndex?:number){setBusy(actionName);setMessage("");const response=await fetch(`/api/v1/workout-sessions/${workout.id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:actionName,...(currentExerciseIndex===undefined?{}:{currentExerciseIndex})})});const payload=await response.json();setBusy("");if(!response.ok){setMessage(payload.errors?.[0]?.message??"No se pudo actualizar");return false;}setWorkout(current=>({...current,...payload.data}));return true}
  async function toggleSet(setNumber:number){const key=`${item.id}:${setNumber}`;const completed=complete.has(key);setBusy(key);const response=await fetch(`/api/v1/workout-sessions/${workout.id}/sets`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({routineExerciseId:item.id,setNumber,completed:!completed,reps:item.reps,durationSeconds:item.durationSeconds})});const payload=await response.json();setBusy("");if(!response.ok){setMessage(payload.errors?.[0]?.message??"No se guardó la serie");return}setWorkout(current=>({...current,setLogs:completed?current.setLogs.filter(log=>!(log.routineExerciseId===item.id&&log.setNumber===setNumber)):[...current.setLogs,{routineExerciseId:item.id,setNumber}]}));if(!completed&&setNumber<item.sets)setRest(item.restSeconds)}
  async function move(next:number){if(next<0||next>=workout.routine.exercises.length)return;if(await action("progress",next))setRest(0)}
  async function finish(){if(!confirm("¿Finalizar tu entrenamiento? Guardaremos el tiempo y todas tus series."))return;if(await action("finish")){router.push(`/rutinas?completed=${workout.id}`);router.refresh()}}
  if(!item)return null;
  return <div className="fixed inset-0 z-[80] flex flex-col overflow-hidden bg-[#030712] text-white">
    <header className="shrink-0 border-b border-slate-800 bg-slate-950/90 px-4 pb-3 pt-[max(1rem,env(safe-area-inset-top))] backdrop-blur-xl"><div className="mx-auto flex max-w-3xl items-center gap-3"><button onClick={()=>router.push("/rutinas")} className="grid h-10 w-10 place-items-center rounded-full bg-slate-900"><X/></button><div className="min-w-0 flex-1"><small className="font-black uppercase tracking-widest text-lime-300">Sesión en vivo</small><strong className="block truncate">{workout.routine.name}</strong></div><div className="rounded-2xl bg-slate-900 px-4 py-2 text-center"><span className="font-mono text-xl font-black text-cyan-300">{clock(elapsed)}</span><small className="block text-[8px] uppercase tracking-widest text-slate-500">tiempo total</small></div></div><div className="mx-auto mt-3 h-1.5 max-w-3xl overflow-hidden rounded-full bg-slate-800"><div className="h-full rounded-full bg-gradient-to-r from-lime-300 to-cyan-300 transition-all" style={{width:`${percentage}%`}}/></div></header>
    <main className="min-h-0 flex-1 overflow-y-auto"><div className="mx-auto max-w-3xl pb-32"><div className="relative h-[38dvh] min-h-64 max-h-[34rem]"><ExerciseVisual licensed={licensed} animated exerciseId={item.exercise.id} name={item.exercise.nameEs||item.exercise.name} className="h-full w-full object-contain"/><div className="absolute inset-x-0 bottom-0 bg-gradient-to-t from-[#030712] via-[#030712]/70 to-transparent px-5 pb-4 pt-20"><p className="text-xs font-black uppercase tracking-[.2em] text-cyan-300">Ejercicio {index+1} de {workout.routine.exercises.length}</p><h1 className="mt-1 text-3xl font-black">{item.exercise.nameEs||item.exercise.name}</h1><p className="mt-1 text-xs capitalize text-slate-400">{item.exercise.target} · {item.exercise.equipment}</p></div></div><section className="px-4"><div className="grid grid-cols-3 gap-2"><div className="rounded-2xl bg-slate-900 p-3 text-center"><strong className="text-lg text-lime-300">{item.sets}</strong><small className="block text-slate-500">series</small></div><div className="rounded-2xl bg-slate-900 p-3 text-center"><strong className="text-lg text-cyan-300">{item.reps??`${item.durationSeconds}s`}</strong><small className="block text-slate-500">{item.reps?"repeticiones":"duración"}</small></div><div className="rounded-2xl bg-slate-900 p-3 text-center"><strong className="text-lg text-orange-300">{item.restSeconds}s</strong><small className="block text-slate-500">descanso</small></div></div><h2 className="mt-6 font-black">Completa tus series</h2><div className="mt-3 grid grid-cols-4 gap-2 sm:grid-cols-6">{Array.from({length:item.sets},(_,i)=>i+1).map(number=>{const checked=complete.has(`${item.id}:${number}`);return <button key={number} disabled={busy===`${item.id}:${number}`} onClick={()=>void toggleSet(number)} className={`aspect-square rounded-2xl border text-center transition ${checked?"border-lime-300 bg-lime-300 text-slate-950":"border-slate-700 bg-slate-900"}`}><span className="mx-auto grid h-7 w-7 place-items-center">{checked?<Check/>:number}</span><small className="text-[9px] font-black">SERIE</small></button>})}</div><details className="mt-6 rounded-2xl border border-slate-800 bg-slate-900/50 p-4"><summary className="cursor-pointer font-black text-slate-200">Cómo hacer este movimiento</summary><ol className="mt-4 space-y-3 text-sm leading-6 text-slate-400">{(item.exercise.instructionStepsEs.length?item.exercise.instructionStepsEs:[item.exercise.instructionsEs]).map((step,i)=><li key={i} className="flex gap-3"><span className="grid h-6 w-6 shrink-0 place-items-center rounded-full bg-cyan-300/10 text-[10px] font-black text-cyan-300">{i+1}</span><span>{step}</span></li>)}</ol></details>{message?<p className="mt-4 rounded-xl bg-red-400/10 p-3 text-center text-xs font-bold text-red-200">{message}</p>:null}</section></div></main>
    <footer className="absolute inset-x-0 bottom-0 border-t border-slate-800 bg-slate-950/95 p-3 pb-[max(.75rem,env(safe-area-inset-bottom))] backdrop-blur-xl"><div className="mx-auto flex max-w-3xl items-center gap-2"><button disabled={index===0} onClick={()=>void move(index-1)} className="grid h-12 w-12 shrink-0 place-items-center rounded-2xl border border-slate-700 disabled:opacity-30"><ArrowLeft/></button><button onClick={()=>void action(workout.status==="ACTIVE"?"pause":"resume")} className="flex h-12 flex-1 items-center justify-center gap-2 rounded-2xl border border-cyan-300/30 bg-cyan-300/10 font-black text-cyan-200">{workout.status==="ACTIVE"?<><CirclePause/> Pausar</>:<><CirclePlay/> Continuar</>}</button>{index<workout.routine.exercises.length-1?<button onClick={()=>void move(index+1)} className="flex h-12 flex-[1.2] items-center justify-center gap-2 rounded-2xl bg-lime-300 font-black text-slate-950">Siguiente <ArrowRight/></button>:<button onClick={()=>void finish()} className="flex h-12 flex-[1.2] items-center justify-center gap-2 rounded-2xl bg-lime-300 font-black text-slate-950"><Flag/> Finalizar</button>}</div></footer>
    {rest>0?<div className="absolute inset-0 z-20 grid place-items-center bg-slate-950/85 p-6 backdrop-blur-xl"><div className="w-full max-w-xs text-center"><span className="mx-auto grid h-20 w-20 place-items-center rounded-full bg-cyan-300/10 text-cyan-300"><Clock3 size={38}/></span><p className="mt-5 text-xs font-black uppercase tracking-[.2em] text-cyan-300">Recupera energía</p><strong className="mt-2 block font-mono text-7xl">{clock(rest)}</strong><p className="mt-3 text-sm text-slate-400">Tu siguiente serie te espera.</p><button onClick={()=>setRest(0)} className="mt-7 inline-flex items-center gap-2 rounded-2xl border border-slate-700 px-6 py-3 font-bold"><RotateCcw size={17}/> Saltar descanso</button></div></div>:null}
  </div>;
}
