import { Activity, Camera, CheckCircle2, Clock3, MapPin } from "lucide-react";
import { prisma } from "@gymchallenge/database";

const statusNames: Record<string, string> = { COMPLETED: "Completada", IN_PROGRESS: "En curso", INVALIDATED: "Invalidada", CANCELED: "Cancelada" };

export default async function AdminAttendances() {
  const rows = await prisma.attendance.findMany({ include: { user: { include: { profile: true } }, photos: { select: { id: true, type: true } } }, orderBy: { createdAt: "desc" }, take: 100 });
  const completed = rows.filter((row) => row.status === "COMPLETED").length;
  return <section><p className="text-xs font-black text-cyan-300">OPERACIÓN DEPORTIVA</p><h1 className="mt-1 text-3xl font-black sm:text-4xl">Asistencias</h1><p className="mt-2 muted">Consulta entrenamientos y evidencias privadas con acceso administrativo.</p>
    <div className="my-7 grid grid-cols-3 gap-3"><article className="card p-4"><Activity size={20} className="text-cyan-300"/><p className="mt-3 text-2xl font-black">{rows.length}</p><p className="text-xs muted">Recientes</p></article><article className="card p-4"><CheckCircle2 size={20} className="text-lime-300"/><p className="mt-3 text-2xl font-black">{completed}</p><p className="text-xs muted">Completadas</p></article><article className="card p-4"><Camera size={20} className="text-violet-300"/><p className="mt-3 text-2xl font-black">{rows.reduce((sum, row) => sum + row.photos.length, 0)}</p><p className="text-xs muted">Evidencias</p></article></div>
    <div className="grid gap-3 md:hidden">{rows.map((row) => <article key={row.id} className="card p-4"><div className="flex items-center gap-3"><span className="grid h-11 w-11 place-items-center rounded-2xl bg-gradient-to-br from-cyan-400 to-lime-400 font-black text-slate-950">{(row.user.profile?.firstName ?? row.user.username).charAt(0)}</span><div className="min-w-0 flex-1"><strong>{row.user.profile?.firstName} {row.user.profile?.lastName}</strong><p className="text-xs muted">@{row.user.username}</p></div><span className="rounded-full bg-slate-800 px-2 py-1 text-[9px] font-black">{statusNames[row.status]}</span></div><div className="mt-4 flex flex-wrap gap-2 text-xs"><span className="inline-flex items-center gap-1 rounded-full bg-slate-950 px-3 py-2"><Clock3 size={13}/>{row.durationMinutes ?? 0} min</span><span className="rounded-full bg-slate-950 px-3 py-2">{row.localDate.toLocaleDateString("es-CO", { timeZone: "UTC" })}</span>{row.startLatitude !== null && <span className="inline-flex items-center gap-1 rounded-full bg-slate-950 px-3 py-2 text-lime-300"><MapPin size={13}/>Ubicación</span>}</div><div className="mt-3 flex gap-2">{row.photos.map((photo) => <a key={photo.id} className="rounded-xl border border-slate-700 px-3 py-2 text-xs font-bold text-cyan-300" href={`/api/v1/attendance-photos/${photo.id}`} target="_blank">Foto {photo.type === "START" ? "inicial" : "final"}</a>)}</div></article>)}</div>
    <div className="card hidden overflow-x-auto md:block"><table className="w-full min-w-[800px] text-left"><thead className="bg-slate-950/70 text-xs text-slate-400"><tr><th className="p-4">Usuario</th><th>Fecha</th><th>Estado</th><th>Duración</th><th>Ubicación</th><th>Evidencias</th></tr></thead><tbody>{rows.map((row) => <tr key={row.id} className="border-t border-slate-800 transition hover:bg-slate-800/30"><td className="p-4"><strong>{row.user.profile?.firstName} {row.user.profile?.lastName}</strong><small className="block muted">@{row.user.username}</small></td><td>{row.localDate.toLocaleDateString("es-CO", { timeZone: "UTC" })}</td><td><span className="rounded-full bg-slate-800 px-2 py-1 text-[10px] font-black">{statusNames[row.status]}</span></td><td>{row.durationMinutes ?? "—"} min</td><td>{row.startLatitude !== null ? <span className="inline-flex items-center gap-1 text-lime-300"><MapPin size={14}/>Registrada</span> : "—"}</td><td>{row.photos.map((photo) => <a key={photo.id} className="mr-2 text-cyan-300 underline" href={`/api/v1/attendance-photos/${photo.id}`} target="_blank">{photo.type === "START" ? "Inicial" : "Final"}</a>)}</td></tr>)}</tbody></table></div>
  </section>;
}
