"use client";

import Link from "next/link";
import { useMemo, useState } from "react";
import { ArrowLeft, ArrowRight, Check, CheckCircle2, Clock3, Flame, Search, ShieldCheck, Sparkles, Swords, Target, UserRound, UserPlus, UsersRound, X } from "lucide-react";

type Category = { id: string; categoryId: string; templateId: string; name: string; description: string; durationDays: number; targetAttendances: number; pointsPerAttendance: number; completionBonus: number };
type Friend = { id: string; username: string; name: string };
type Invitation = { id: string; category: string; creator: string };

export function ChallengeActions({ categories, friends, invitations, initialTemplateId }: { categories: Category[]; friends: Friend[]; invitations: Invitation[]; initialTemplateId?: string }) {
  const [step, setStep] = useState(initialTemplateId ? 1 : 1);
  const [mode, setMode] = useState<"solo" | "social">("social");
  const [message, setMessage] = useState("");
  const [query, setQuery] = useState("");
  const [templateQuery, setTemplateQuery] = useState("");
  const [selectedFriends, setSelectedFriends] = useState<string[]>([]);
  const [categoryId, setCategoryId] = useState(categories.find((item) => item.templateId === initialTemplateId)?.id ?? "");
  const [busy, setBusy] = useState(false);
  const selectedCategory = categories.find((category) => category.id === categoryId);
  const visibleFriends = friends.filter((friend) => `${friend.name} ${friend.username}`.toLowerCase().includes(query.trim().toLowerCase()));
  const visibleCategories = useMemo(() => categories.filter((category) => `${category.name} ${category.description}`.toLowerCase().includes(templateQuery.trim().toLowerCase())), [categories, templateQuery]);

  async function action(body: object) {
    setBusy(true); setMessage("");
    const response = await fetch("/api/v1/challenges", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(body) });
    const json = await response.json() as { message: string; errors?: Array<{ message: string }> };
    setBusy(false); setMessage(response.ok ? json.message : (json.errors?.[0]?.message ?? json.message));
    if (response.ok) setTimeout(() => location.reload(), 850);
  }

  function toggleFriend(id: string) {
    setMessage("");
    setSelectedFriends((current) => {
      if (current.includes(id)) return current.filter((value) => value !== id);
      if (current.length >= 3) { setMessage("Tu equipo ya está completo: máximo 3 amigos."); return current; }
      return [...current, id];
    });
  }

  function continueWizard() {
    setMessage("");
    if (step === 2 && !categoryId) { setMessage("Elige el reto que quieres comenzar."); return; }
    if (step === 3 && mode === "social" && selectedFriends.length === 0) { setMessage("Selecciona al menos un amigo para formar el equipo."); return; }
    setStep((value) => Math.min(3, value + 1));
  }

  return <div className="mb-9 space-y-6">
    {invitations.length > 0 && <section className="overflow-hidden rounded-[28px] border border-orange-400/30 bg-gradient-to-br from-orange-400/10 via-slate-900 to-lime-400/5"><div className="flex items-center gap-3 border-b border-orange-400/20 p-5"><span className="grid h-11 w-11 place-items-center rounded-2xl bg-orange-400 text-slate-950"><Swords/></span><div><p className="text-xs font-bold text-orange-300">INVITACIONES</p><h2 className="text-xl font-black">Tu próximo reto te espera</h2></div><span className="ml-auto rounded-full bg-orange-400 px-3 py-1 text-xs font-black text-slate-950">{invitations.length}</span></div><div className="grid gap-3 p-4 sm:grid-cols-2">{invitations.map((invitation) => <article key={invitation.id} className="rounded-2xl border border-slate-700 bg-slate-950/80 p-4"><div className="flex items-start gap-3"><div className="grid h-11 w-11 shrink-0 place-items-center rounded-2xl bg-gradient-to-br from-orange-400 to-lime-400 font-black text-slate-950">{invitation.creator.charAt(0)}</div><div><p><strong>{invitation.creator}</strong> te invitó</p><p className="mt-1 text-sm text-orange-300">{invitation.category}</p></div></div><button disabled={busy} onClick={() => action({ action: "accept", challengeId: invitation.id })} className="btn mt-4 w-full gap-2"><Check size={18}/>Aceptar reto</button></article>)}</div></section>}

    <section className="overflow-hidden rounded-[30px] border border-slate-700 bg-gradient-to-br from-slate-900 via-slate-900 to-violet-950/25 shadow-[0_28px_90px_rgba(0,0,0,.22)]">
      <header className="border-b border-slate-800 bg-gradient-to-r from-lime-400/10 via-cyan-400/[.04] to-orange-400/10 p-5 sm:p-7">
        <div className="flex flex-wrap items-start justify-between gap-4"><div><span className="inline-flex items-center gap-2 rounded-full bg-lime-400/10 px-3 py-1.5 text-[10px] font-black tracking-wider text-lime-300"><Sparkles size={14}/>CREADOR DE RETOS</span><h2 className="mt-3 text-3xl font-black">Crea algo que te mueva.</h2><p className="mt-2 max-w-xl text-sm muted">En tres pasos tendrás una meta personal o una competencia lista para comenzar.</p></div><span className="rounded-2xl border border-slate-700 bg-slate-950/75 px-4 py-3 text-sm font-black">Paso {step} de 3</span></div>
        <div className="mt-5 grid grid-cols-3 gap-2">{["Modalidad", "Reto", "Equipo"].map((label, index) => { const number=index+1; return <button type="button" key={label} onClick={() => number < step && setStep(number)} className="text-left"><span className={`block h-1.5 rounded-full ${number <= step ? "bg-gradient-to-r from-lime-400 to-cyan-400" : "bg-slate-700"}`}/><span className={`mt-2 block text-[10px] font-black ${number === step ? "text-lime-300" : "text-slate-500"}`}>{number}. {label}</span></button>; })}</div>
      </header>

      <div className="p-5 sm:p-7">
        {step === 1 && <div><p className="text-xs font-black text-lime-300">¿CÓMO QUIERES VIVIRLO?</p><h3 className="mt-1 text-2xl font-black">Elige tu modalidad</h3><p className="mt-1 text-sm muted">Puedes construir disciplina a tu ritmo o compartir la energía con amigos.</p><div className="mt-6 grid gap-4 md:grid-cols-2"><button type="button" onClick={() => { setMode("solo"); setSelectedFriends([]); }} className={`relative overflow-hidden rounded-[26px] border p-6 text-left transition ${mode === "solo" ? "border-lime-300 bg-lime-300 text-slate-950 shadow-[0_0_34px_rgba(163,230,53,.15)]" : "border-slate-700 bg-slate-950/55 hover:border-lime-400/50"}`}><span className={`grid h-14 w-14 place-items-center rounded-2xl ${mode === "solo" ? "bg-slate-950 text-lime-300" : "bg-lime-400/10 text-lime-300"}`}><UserRound size={27}/></span><strong className="mt-5 block text-xl">Reto personal</strong><p className={`mt-2 text-sm ${mode === "solo" ? "text-slate-800" : "muted"}`}>Una meta solo para ti. Comienza de inmediato y compite con tu versión de ayer.</p>{mode === "solo" && <CheckCircle2 className="absolute right-5 top-5"/>}</button><button type="button" onClick={() => setMode("social")} className={`relative overflow-hidden rounded-[26px] border p-6 text-left transition ${mode === "social" ? "border-cyan-300 bg-cyan-300 text-slate-950 shadow-[0_0_34px_rgba(34,211,238,.13)]" : "border-slate-700 bg-slate-950/55 hover:border-cyan-400/50"}`}><span className={`grid h-14 w-14 place-items-center rounded-2xl ${mode === "social" ? "bg-slate-950 text-cyan-300" : "bg-cyan-400/10 text-cyan-300"}`}><UsersRound size={27}/></span><strong className="mt-5 block text-xl">Reto con amigos</strong><p className={`mt-2 text-sm ${mode === "social" ? "text-slate-800" : "muted"}`}>Invita hasta tres amigos. El reto se activa cuando todo el equipo acepta.</p>{mode === "social" && <CheckCircle2 className="absolute right-5 top-5"/>}</button></div></div>}

        {step === 2 && <div><p className="text-xs font-black text-orange-300">ELIGE TU ENERGÍA</p><h3 className="mt-1 text-2xl font-black">¿Qué quieres conquistar?</h3><p className="mt-1 text-sm muted">Estas configuraciones son oficiales y sus reglas quedan guardadas al crear tu reto.</p><label className="mt-5 flex items-center gap-3 rounded-2xl border border-slate-700 bg-slate-950 px-4 focus-within:border-orange-400"><Search size={18} className="text-slate-500"/><input value={templateQuery} onChange={(event) => setTemplateQuery(event.target.value)} placeholder="Buscar por nombre o descripción" className="w-full bg-transparent py-3.5 outline-none"/>{templateQuery && <button type="button" onClick={() => setTemplateQuery("")} aria-label="Limpiar búsqueda"><X size={17}/></button>}</label><div className="mt-4 grid gap-3 md:grid-cols-2">{visibleCategories.map((category) => { const selected=category.id===categoryId; return <button type="button" key={category.id} onClick={() => setCategoryId(category.id)} className={`relative rounded-[22px] border p-4 text-left transition ${selected ? "border-orange-300 bg-orange-400/10" : "border-slate-800 bg-slate-950/55 hover:border-slate-600"}`}><div className="flex gap-3"><span className={`grid h-12 w-12 shrink-0 place-items-center rounded-2xl ${selected ? "bg-orange-400 text-slate-950" : "bg-orange-400/10 text-orange-300"}`}><Flame/></span><span className="min-w-0"><strong className="block text-lg">{category.name}</strong><p className="mt-1 line-clamp-2 text-xs muted">{category.description}</p></span>{selected && <CheckCircle2 className="ml-auto shrink-0 text-orange-300"/>}</div><div className="mt-4 flex flex-wrap gap-2 text-[10px]"><span className="rounded-full bg-slate-950 px-2.5 py-1.5"><Clock3 size={11} className="mr-1 inline"/>{category.durationDays} días</span><span className="rounded-full bg-slate-950 px-2.5 py-1.5"><Target size={11} className="mr-1 inline"/>{category.targetAttendances} asistencias</span><span className="rounded-full bg-slate-950 px-2.5 py-1.5">+{category.pointsPerAttendance} pts</span></div></button>; })}</div>{visibleCategories.length===0 && <p className="mt-4 rounded-2xl border border-dashed border-slate-700 p-6 text-center text-sm muted">No encontramos un reto con esa búsqueda.</p>}</div>}

        {step === 3 && <div><p className="text-xs font-black text-cyan-300">ÚLTIMO PASO</p><h3 className="mt-1 text-2xl font-black">{mode === "solo" ? "Revisa tu nueva meta" : "Forma tu equipo"}</h3><p className="mt-1 text-sm muted">{mode === "solo" ? "Tu reto comenzará cuando confirmes." : "Selecciona entre uno y tres amigos para enviarles la invitación."}</p>{mode === "social" && <><label className="mt-5 flex items-center gap-3 rounded-2xl border border-slate-700 bg-slate-950 px-4 focus-within:border-cyan-400"><Search size={18} className="text-slate-500"/><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Buscar entre tus amigos" className="w-full bg-transparent py-3.5 outline-none"/><span className="shrink-0 rounded-full bg-cyan-400/10 px-2.5 py-1 text-[10px] font-black text-cyan-300">{selectedFriends.length}/3</span></label><div className="mt-4 grid max-h-64 gap-2 overflow-y-auto pr-1 sm:grid-cols-2">{friends.length===0 ? <div className="col-span-2 rounded-2xl border border-dashed border-slate-700 p-6 text-center"><UserPlus className="mx-auto text-slate-600"/><p className="mt-3 font-bold">Tu equipo comienza en Comunidad</p><Link href="/comunidad" className="mt-2 inline-block text-sm font-bold text-lime-300">Buscar amigos</Link></div> : visibleFriends.map((friend) => { const selected=selectedFriends.includes(friend.id); return <button type="button" key={friend.id} onClick={() => toggleFriend(friend.id)} className={`flex items-center gap-3 rounded-2xl border p-3 text-left ${selected ? "border-cyan-300 bg-cyan-400/10" : "border-slate-800 bg-slate-950/60"}`}><span className={`grid h-10 w-10 place-items-center rounded-xl font-black ${selected ? "bg-cyan-300 text-slate-950" : "bg-slate-800"}`}>{friend.name.charAt(0)}</span><span className="min-w-0 flex-1"><strong className="block truncate">{friend.name}</strong><small className="muted">@{friend.username}</small></span>{selected ? <CheckCircle2 className="text-cyan-300"/> : <UserPlus size={16} className="text-slate-500"/>}</button>; })}</div></>}
          {selectedCategory && <div className="mt-5 overflow-hidden rounded-[24px] border border-lime-400/20 bg-gradient-to-r from-lime-400/[.08] to-cyan-400/[.05] p-5"><div className="flex items-start gap-3"><span className="grid h-12 w-12 shrink-0 place-items-center rounded-2xl bg-orange-400 text-slate-950"><Flame/></span><div><p className="text-[10px] font-black tracking-wider text-lime-300">TU RETO ESTÁ LISTO</p><h4 className="mt-1 text-xl font-black">{selectedCategory.name}</h4><p className="mt-1 text-sm muted">{mode === "solo" ? "Personal" : `${selectedFriends.length} ${selectedFriends.length===1?"amigo":"amigos"}`} · {selectedCategory.durationDays} días · meta {selectedCategory.targetAttendances}</p></div></div><div className="mt-4 flex items-start gap-2 rounded-2xl bg-slate-950/65 p-3 text-xs muted"><ShieldCheck size={17} className="shrink-0 text-lime-300"/>Tus fotografías y ubicaciones conservan la privacidad configurada para los participantes del reto.</div></div>}
        </div>}

        {message && <p role="status" className="mt-5 rounded-2xl border border-slate-700 bg-slate-950 p-4 text-center text-sm font-bold text-orange-200">{message}</p>}
        <div className="mt-6 flex gap-3 border-t border-slate-800 pt-5">{step>1 && <button type="button" onClick={() => { setStep((value)=>value-1); setMessage(""); }} className="inline-flex flex-1 items-center justify-center gap-2 rounded-2xl border border-slate-700 py-3.5 font-bold"><ArrowLeft size={18}/>Atrás</button>}{step<3 ? <button type="button" onClick={continueWizard} className="btn flex-[1.5] gap-2 py-3.5">Continuar<ArrowRight size={18}/></button> : <button type="button" disabled={busy || !selectedCategory || (mode==="social"&&selectedFriends.length===0)} onClick={() => void action({ action:"create", categoryId:selectedCategory?.categoryId, templateId:selectedCategory?.templateId, targetIds: mode==="solo" ? [] : selectedFriends })} className="btn flex-[1.5] gap-2 py-3.5"><Swords size={19}/>{busy ? "Creando…" : mode==="solo" ? "Comenzar mi reto" : "Enviar invitación"}</button>}</div>
      </div>
    </section>
  </div>;
}
