import { notFound, redirect } from "next/navigation";
import Link from "next/link";
import { getServerSession } from "next-auth";
import { prisma } from "@gymchallenge/database";
import { ArrowLeft, Clock3, Dumbbell, Gauge, Repeat2, Timer } from "lucide-react";
import { authOptions } from "@/lib/auth";
import { ExerciseVisual } from "@/components/routines/exercise-visual";
import { StartRoutineButton } from "@/components/routines/start-routine-button";
import { routineInclude } from "@/modules/routines/queries";

export default async function RoutineDetail({ params }: { params: Promise<{ slug: string }> }) {
  const auth = await getServerSession(authOptions); const { slug } = await params;
  if (!auth) redirect("/login");
  const routine = await prisma.routine.findFirst({ where: { slug, OR: [{ isPublic: true }, { ownerId: auth.user.id }] }, include: routineInclude });
  if (!routine) notFound(); const licensed=process.env.EXERCISE_MEDIA_LICENSED==="1";
  return <div className="mx-auto max-w-3xl pb-10"><Link href="/rutinas" className="inline-flex items-center gap-2 text-sm font-bold text-slate-400"><ArrowLeft size={17}/> Rutinas</Link><header className="mt-5 rounded-[2rem] border border-slate-700 bg-[linear-gradient(145deg,rgba(163,230,53,.11),rgba(34,211,238,.04),#080f1d)] p-6 sm:p-8"><p className="text-xs font-black uppercase tracking-[.2em] text-lime-300">{routine.goal}</p><h1 className="mt-2 text-4xl font-black">{routine.name}</h1><p className="mt-3 leading-6 text-slate-300">{routine.description}</p><div className="mt-5 grid grid-cols-3 gap-2 text-center"><span className="rounded-2xl bg-black/25 p-3"><Clock3 className="mx-auto text-cyan-300" size={20}/><strong className="mt-1 block">{routine.estimatedMinutes}</strong><small className="text-slate-500">minutos</small></span><span className="rounded-2xl bg-black/25 p-3"><Dumbbell className="mx-auto text-lime-300" size={20}/><strong className="mt-1 block">{routine.exercises.length}</strong><small className="text-slate-500">ejercicios</small></span><span className="rounded-2xl bg-black/25 p-3"><Gauge className="mx-auto text-orange-300" size={20}/><strong className="mt-1 block text-xs">{routine.difficulty==="BEGINNER"?"Inicial":routine.difficulty==="INTERMEDIATE"?"Media":"Avanzada"}</strong><small className="text-slate-500">nivel</small></span></div><div className="mt-6"><StartRoutineButton routineId={routine.id}/></div></header><section className="mt-8"><p className="text-xs font-black uppercase tracking-[.18em] text-cyan-300">Tu recorrido</p><h2 className="mt-1 text-2xl font-black">Ejercicios de hoy</h2><div className="mt-4 space-y-3">{routine.exercises.map((item,index)=><article key={item.id} className="flex gap-4 rounded-[1.5rem] border border-slate-800 bg-slate-900/70 p-3"><div className="h-24 w-24 shrink-0 overflow-hidden rounded-2xl"><ExerciseVisual licensed={licensed} exerciseId={item.exercise.id} name={item.exercise.nameEs||item.exercise.name} className="h-full w-full"/></div><div className="min-w-0 flex-1 py-1"><small className="font-black text-lime-300">{String(index+1).padStart(2,"0")}</small><h3 className="truncate font-black">{item.exercise.nameEs||item.exercise.name}</h3><p className="mt-1 text-xs capitalize text-slate-500">{item.exercise.target} · {item.exercise.equipment}</p><div className="mt-2 flex gap-3 text-[11px] font-bold text-slate-300"><span><Repeat2 size={12} className="mr-1 inline"/>{item.sets} series × {item.reps??`${item.durationSeconds}s`}</span><span><Timer size={12} className="mr-1 inline"/>{item.restSeconds}s descanso</span></div></div></article>)}</div></section></div>;
}
